apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviewservice
  template:
    metadata:
      labels:
        app: reviewservice
    spec:
      containers:
        - name: reviewservice
          image: registry.gitlab.com/<group>/<project>/reviewservice:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: reviewservice
spec:
  ports:
    - port: 8080
  selector:
    app: reviewservice
