version: "3.9"

services:
  app:
    image: ghcr.io/Arpitmovers/reviewService/reviewservice:latest
    container_name: reviewservice
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: reviewuser
      DB_PASSWORD: reviewpass
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - redis
      - rabbitmq
    networks:
      - backend

  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: reviewdb
      MYSQL_USER: reviewuser
      MYSQL_PASSWORD: reviewpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
    driver: bridge
