name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest  s

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -f deploy/Dockerfile -t ghcr.io/arpitmovers/reviewservice/reviewservice:latest .
    
    - name: Push Docker image
        run: docker push ghcr.io/arpitmovers/reviewservice/reviewservice:latest

